### ISSUE TITLE
3box plugin: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by gpersoon** [ethereum/remix-plugin#131] opened 2019-09-07 08:31 UTC
This a followup on: https://github.com/ethereum/remix-plugin/issues/130

After having made a login account and trying to login to 3Box in de 3Box plugin in
http://remix.ethereum.org : 
Nothing happens and in the console of the developer tools the following is shown:
```js
main.js:79 Uncaught TypeError: Cannot read property 'importKey' of undefined
```

Workaround: use https://remix.ethereum.org

**Comment by GrandSchtroumpf** [comment] 2019-09-16 14:04
duplicate of #130 as it related to the same issue. Feel free to reopen if you consider it to be different.

**Closed by GrandSchtroumpf** 2019-09-16 14:04 UTC
