### ISSUE TITLE
 client.call('udapp', 'sendTransaction',tx) returns undefined

### ISSUE THREAD

**Issue by allemanfredi** [ethereum/remix-plugin#145] opened 2019-10-08 17:37 UTC
Hello,

I'm trying to send a transaction with the following code but it returns always `undefined`

```js
const tx: RemixTx = {
  gasLimit: '300000000',
  from: '0x265a5c3dd46ec82e2744f1d0e9fb4ed75d56132a',
  to: '0x51efaf4c8b3c9afbd5ab9f4bbc82784ab6ef8faa',
  data: '0xd1d80fdf00000000000000000000000074c65624deafb25864108d2491fc7093a540bc03'
  value: '0',
  useCall: false
}
await remixClient.call('udapp', 'sendTransaction', tx)
```

**Comment by edevil** [comment] 2019-10-14 10:48
I'm also affected by this issue since it happens with the provable remix plugin.

**Comment by GrandSchtroumpf** [comment] 2019-10-17 10:39
I cannot reproduce. So here is a working example : 
1. Create a Smart contract 
```sol
pragma solidity >= 0.5.0 <0.6.0;
contract Test {
    string public value;
    function setValue(string memory _value) public {
        value = _value;
    }
}
```

2. Compile and Deploy
Copy the address, in my case "0x692a70D2e424a56D2C6C27aA97D1a86395877b3A"

3. In your plugin
```javascript
const tx = {
  data: "0x93a093520000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b48656c6c6f20576f726c64000000000000000000000000000000000000000000",  // Call function `setValue` with argument "Hello World"
  from: "0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c",  // address of the account
  gasLimit: "0x2dc6c0",
  to: "0x692a70D2e424a56D2C6C27aA97D1a86395877b3A",  // address of the contract
  useCall: false,  // this is a transaction
  value: "0" 
}
const result = await client.call('udapp', 'sendTransaction', tx)
console.log(result) // {"transactionHash":"...","status":"0x1","gasUsed":"0x5cb3","error":null,"return":"0x"}
```

Let me know if this doesn't work

**Comment by allemanfredi** [comment] 2019-10-17 12:02
By reading your code i found this [commit](https://github.com/ethereum/remix-plugin/commit/ba1d1b897ff89152388080e865e7743a1d5a4822) in which I see that the properties of the object are different from the ones I am actually using. Could be a problem?

**Comment by GrandSchtroumpf** [comment] 2019-10-17 12:08
No, this commit should apply to the event `newTransaction` but I accidentaly removed the previous RemixTx for the `sendTransaction`. I'll update that, thanks for reporting.
The above example should work. Can you reproduce ?

**Comment by allemanfredi** [comment] 2019-10-17 12:14
In practise what i'm trying to do is to deploy a smart contract via transaction by putting the bytecode within `data` field. First of all i create an account with `createVMAccount` which works, then i deploy the contract with a transaction having `from` field equal to the address just created. The problem is that it has always worked, it has stopped working recently

**Comment by GrandSchtroumpf** [comment] 2019-10-17 12:22
Hmm it works for me like that :
```javascript
const receipt = await client.call('udapp', 'sendTransaction', {
data: "0x608060405234801561001057600080fd5b5061030b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633fa4f2451461003b57806393a09352146100be575b600080fd5b610043610179565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610083578082015181840152602081019050610068565b50505050905090810190601f1680156100b05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610177600480360360208110156100d457600080fd5b81019080803590602001906401000000008111156100f157600080fd5b82018360208201111561010357600080fd5b8035906020019184600183028401116401000000008311171561012557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610217565b005b60008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561020f5780601f106101e45761010080835404028352916020019161020f565b820191906000526020600020905b8154815290600101906020018083116101f257829003601f168201915b505050505081565b806000908051906020019061022d929190610231565b5050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061027257805160ff19168380011785556102a0565b828001600101855582156102a0579182015b8281111561029f578251825591602001919060010190610284565b5b5090506102ad91906102b1565b5090565b6102d391905b808211156102cf5760008160009055506001016102b7565b5090565b9056fea265627a7a72315820c71147fc3334f6cad8f3f8ca98bf85da92cb37baa698581f10d8e7c5b4aa7e5264736f6c634300050b0032",
from: "0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c",
gasLimit: "0x2dc6c0",
useCall: false,
value: "0"
});
console.log(receipt) // { transactionHash: "...", status: "0x1", gasUsed: "0x3fbd6", error: null, return: "...", createdAddress: "0x0dcd2f752394c41875e259e00bb44fd505297caf"}
```

**Comment by allemanfredi** [comment] 2019-10-17 12:27
thank you very much but it returns `undefined` again. Which version are you using?

**Comment by GrandSchtroumpf** [comment] 2019-10-17 12:28
0.1.18

**Comment by allemanfredi** [comment] 2019-10-17 12:32
Nothing! even updating the package I always get the usual mistake! keep trying! if I find the error I will let you know! thank you very much again!

**Comment by GrandSchtroumpf** [comment] 2019-10-17 12:36
Ok can you try that :
1. Create a `index.html` :
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <button class="btn" onclick="deploy()">Deploy contract</button>
  <script src="https://unpkg.com/@remixproject/plugin"></script>
  <script>
    const { createIframeClient } = remixPlugin
    const client = createIframeClient()

    async function deploy() {
      await client.onload();
      const receipt = await client.call('udapp', 'sendTransaction', {
        data: "0x608060405234801561001057600080fd5b5061030b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633fa4f2451461003b57806393a09352146100be575b600080fd5b610043610179565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610083578082015181840152602081019050610068565b50505050905090810190601f1680156100b05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610177600480360360208110156100d457600080fd5b81019080803590602001906401000000008111156100f157600080fd5b82018360208201111561010357600080fd5b8035906020019184600183028401116401000000008311171561012557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610217565b005b60008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561020f5780601f106101e45761010080835404028352916020019161020f565b820191906000526020600020905b8154815290600101906020018083116101f257829003601f168201915b505050505081565b806000908051906020019061022d929190610231565b5050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061027257805160ff19168380011785556102a0565b828001600101855582156102a0579182015b8281111561029f578251825591602001919060010190610284565b5b5090506102ad91906102b1565b5090565b6102d391905b808211156102cf5760008160009055506001016102b7565b5090565b9056fea265627a7a72315820c71147fc3334f6cad8f3f8ca98bf85da92cb37baa698581f10d8e7c5b4aa7e5264736f6c634300050b0032",
        from: "0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c",
        gasLimit: "0x2dc6c0",
        useCall: false,
        value: "0"
      });
      console.log(receipt)
    }
  </script>
</body>

</html>
```
2. run `npx live-server`
3. In remix-ide connect to local plugin with `http://localhost:8080` (or the port used with live-server)
4. Hit "deploy contract" button and look into the console

**Comment by allemanfredi** [comment] 2019-10-17 12:48
It works! thank you! By replacing your bytecode with my receive `out of gas`. It is strange though that before I did not receive this error using the same `gas limit`

**Comment by GrandSchtroumpf** [comment] 2019-10-17 12:51
The `out of gas` may come from the size of your contract. My example is a super small contract that doesn't require a lot of gas.
I'll close this issue. Feel free to reopen if you consider that it's not resolved.

**Closed by GrandSchtroumpf** 2019-10-17 12:51 UTC
